/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _ida;
import 'package:discoman_client/src/protocol/execution/models/claimed_execution.dart'
    as _il9ps7wn;
import 'package:discoman_client/src/protocol/execution/models/compute_client_credential_info.dart'
    as _iywakebc;
import 'package:discoman_client/src/protocol/execution/models/compute_mode.dart'
    as _ibr0is37;
import 'package:discoman_client/src/protocol/execution/models/compute_worker_info.dart'
    as _iu3gutcn;
import 'package:discoman_client/src/protocol/execution/models/created_compute_client_credential.dart'
    as _iqpenjjc;
import 'package:discoman_client/src/protocol/execution/models/creator_compute_settings.dart'
    as _il57mzp3;
import 'package:discoman_client/src/protocol/execution/models/execution_asset_ref.dart'
    as _ioaawgzi;
import 'package:discoman_client/src/protocol/execution/models/execution_asset_upload.dart'
    as _itmbcnyn;
import 'package:discoman_client/src/protocol/execution/models/execution_outcome.dart'
    as _iftp3wwi;
import 'package:discoman_client/src/protocol/execution/models/heartbeat_response.dart'
    as _irjjqoev;
import 'package:discoman_client/src/protocol/execution/models/worker_registration.dart'
    as _inbbf50m;
import 'package:discoman_client/src/protocol/runtime/contract_draft.dart'
    as _idmvvsng;
import 'package:discoman_client/src/protocol/runtime/creator_project_summary.dart'
    as _i4qtshzf;
import 'package:http/http.dart' as _i85jenna;
import 'package:serverpod_auth_core_client/serverpod_auth_core_client.dart'
    as _iacc;
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _iaic;
import 'package:serverpod_client/serverpod_client.dart' as _isc;
import 'protocol.dart' as _il2as5qe;

/// By extending [FirebaseIdpBaseEndpoint], the Firebase identity provider
/// endpoint is made available on the server.
///
/// The app signs the user in with Firebase (email/password, or anonymously for
/// public app pages) and exchanges the resulting Firebase ID token here, once,
/// for a Serverpod session. Every subsequent call carries the Serverpod token
/// instead, so the backend authenticates against a session it owns — and can
/// therefore revoke.
/// {@category Endpoint}
class EndpointFirebaseIdp extends _iaic.EndpointFirebaseIdpBase {
  EndpointFirebaseIdp(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'firebaseIdp';

  @override
  _ida.Future<_iacc.AuthSuccess> login({required String idToken}) =>
      caller.callServerEndpoint<_iacc.AuthSuccess>(
        'firebaseIdp',
        'login',
        {'idToken': idToken},
      );

  @override
  _ida.Future<bool> hasAccount() => caller.callServerEndpoint<bool>(
    'firebaseIdp',
    'hasAccount',
    {},
  );
}

/// By extending [RefreshJwtTokensEndpoint], the JWT token refresh endpoint
/// is made available on the server and enables automatic token refresh on the client.
/// {@category Endpoint}
class EndpointJwtRefresh extends _iacc.EndpointRefreshJwtTokens {
  EndpointJwtRefresh(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'jwtRefresh';

  /// Creates a new token pair for the given [refreshToken].
  ///
  /// If [refreshToken] is omitted, cookie-mode web clients fall back to the
  /// configured HttpOnly refresh cookie. When neither source is present this
  /// throws [RefreshTokenNotFoundException], the same public "no usable refresh
  /// credential" exception used for unknown refresh tokens.
  ///
  /// Can throw the following exceptions:
  /// -[RefreshTokenMalformedException]: refresh token is malformed and could
  ///   not be parsed. Not expected to happen for tokens issued by the server.
  /// -[RefreshTokenNotFoundException]: refresh token is unknown to the server.
  ///   Either the token was deleted or generated by a different server.
  /// -[RefreshTokenExpiredException]: refresh token has expired. Will happen
  ///   only if it has not been used within configured `refreshTokenLifetime`.
  /// -[RefreshTokenInvalidSecretException]: refresh token is incorrect, meaning
  ///   it does not refer to the current secret refresh token. This indicates
  ///   either a malfunctioning client or a malicious attempt by someone who has
  ///   obtained the refresh token. In this case the underlying refresh token
  ///   will be deleted, and access to it will expire fully when the last access
  ///   token is elapsed.
  ///
  /// This endpoint is unauthenticated, meaning the client won't include any
  /// authentication information with the call.
  @override
  _ida.Future<_iacc.AuthSuccess> refreshAccessToken({String? refreshToken}) =>
      caller.callServerEndpoint<_iacc.AuthSuccess>(
        'jwtRefresh',
        'refreshAccessToken',
        {'refreshToken': refreshToken},
        authenticated: false,
      );
}

/// Creator-facing compute configuration: where their executions run (cloud or
/// their own machine), their self-hosted limits, their live workers, and the
/// machine credentials their compute clients authenticate with.
/// {@category Endpoint}
class EndpointComputeSettings extends _isc.EndpointRef {
  EndpointComputeSettings(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'computeSettings';

  /// Returns the caller's compute settings, materializing the defaults on
  /// first read.
  _ida.Future<_il57mzp3.CreatorComputeSettings> getMySettings() =>
      caller.callServerEndpoint<_il57mzp3.CreatorComputeSettings>(
        'computeSettings',
        'getMySettings',
        {},
      );

  /// Switches the caller's executions between the cloud pool and their own
  /// machine. Applies to runs submitted from now on; queued runs keep the
  /// lane they were submitted in.
  _ida.Future<_il57mzp3.CreatorComputeSettings> setComputeMode(
    _ibr0is37.ComputeMode mode,
  ) => caller.callServerEndpoint<_il57mzp3.CreatorComputeSettings>(
    'computeSettings',
    'setComputeMode',
    {'mode': mode},
  );

  /// The caller's own compute workers (self-hosted clients), newest first.
  _ida.Future<List<_iu3gutcn.ComputeWorkerInfo>> listMyWorkers() =>
      caller.callServerEndpoint<List<_iu3gutcn.ComputeWorkerInfo>>(
        'computeSettings',
        'listMyWorkers',
        {},
      );

  /// Mints a new machine credential for the caller's compute client. The
  /// plaintext token is returned exactly once; only its hash is stored.
  _ida.Future<_iqpenjjc.CreatedComputeClientCredential>
  createComputeClientCredential(String name) =>
      caller.callServerEndpoint<_iqpenjjc.CreatedComputeClientCredential>(
        'computeSettings',
        'createComputeClientCredential',
        {'name': name},
      );

  /// The caller's machine credentials, newest first.
  _ida.Future<List<_iywakebc.ComputeClientCredentialInfo>>
  listComputeClientCredentials() =>
      caller.callServerEndpoint<List<_iywakebc.ComputeClientCredentialInfo>>(
        'computeSettings',
        'listComputeClientCredentials',
        {},
      );

  /// Revokes a machine credential and kills its live sessions (the JWT
  /// refresh tokens of its dedicated AuthUser).
  _ida.Future<void> revokeComputeClientCredential(
    _isc.UuidValue credentialId,
  ) => caller.callServerEndpoint<void>(
    'computeSettings',
    'revokeComputeClientCredential',
    {'credentialId': credentialId},
  );
}

/// The worker protocol, shared by the cloud Container App Job pool and the
/// remote compute client on a creator's machine: register, claim, heartbeat,
/// upload output assets, report the result.
///
/// Postgres is the source of truth throughout: claims are atomic row updates
/// with a lease, and everything a worker sends is re-validated server-side.
/// {@category Endpoint}
class EndpointComputeWorker extends _isc.EndpointRef {
  EndpointComputeWorker(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'computeWorker';

  /// Registers a worker process and returns the heartbeat/lease cadence it
  /// must follow.
  _ida.Future<_inbbf50m.WorkerRegistration> register(
    String? hostname,
    String? version,
  ) => caller.callServerEndpoint<_inbbf50m.WorkerRegistration>(
    'computeWorker',
    'register',
    {
      'hostname': hostname,
      'version': version,
    },
  );

  /// Atomically claims the next runnable execution in the caller's lane, or
  /// returns null when nothing is claimable.
  ///
  /// [servedProjectIds] is how a self-hosted worker says which projects it can
  /// run: the ones whose script the creator has linked on that machine, and
  /// has left switched on. Sent on every claim rather than stored, so linking a
  /// script on a second computer takes effect on its next poll with nothing to
  /// register or refresh. Ignored for cloud workers, which run whatever the
  /// row carries.
  _ida.Future<_il9ps7wn.ClaimedExecution?> claimNext(
    _isc.UuidValue workerId,
    List<String> servedProjectIds,
  ) => caller.callServerEndpoint<_il9ps7wn.ClaimedExecution?>(
    'computeWorker',
    'claimNext',
    {
      'workerId': workerId,
      'servedProjectIds': servedProjectIds,
    },
  );

  /// Worker liveness plus lease renewal for the execution it is running.
  /// `cancelRequested: true` also doubles as the stop signal when the lease
  /// was lost (the sweeper already gave the run away).
  _ida.Future<_irjjqoev.HeartbeatResponse> heartbeat(
    _isc.UuidValue workerId,
    _isc.UuidValue? executionId,
  ) => caller.callServerEndpoint<_irjjqoev.HeartbeatResponse>(
    'computeWorker',
    'heartbeat',
    {
      'workerId': workerId,
      'executionId': executionId,
    },
  );

  /// Stores one output asset for the claimed execution in Firebase Storage
  /// and returns the reference the worker must substitute into its outputs.
  ///
  /// Everything is enforced server-side: ownership, per-kind size caps,
  /// base64-length reconciliation, and per-execution asset count/byte caps.
  _ida.Future<_ioaawgzi.ExecutionAssetRef> uploadExecutionAsset(
    _isc.UuidValue workerId,
    _isc.UuidValue executionId,
    _itmbcnyn.ExecutionAssetUpload asset,
  ) => caller.callServerEndpoint<_ioaawgzi.ExecutionAssetRef>(
    'computeWorker',
    'uploadExecutionAsset',
    {
      'workerId': workerId,
      'executionId': executionId,
      'asset': asset,
    },
  );

  /// Finalizes a claimed execution with the worker's outcome. Exactly-once:
  /// stale or duplicate reports are no-ops. On success of a published-app run
  /// the Firestore history/usage documents are written afterwards —
  /// best-effort, exactly as the legacy synchronous path did.
  _ida.Future<void> reportResult(
    _isc.UuidValue workerId,
    _isc.UuidValue executionId,
    _iftp3wwi.ExecutionOutcome outcome,
  ) => caller.callServerEndpoint<void>(
    'computeWorker',
    'reportResult',
    {
      'workerId': workerId,
      'executionId': executionId,
      'outcome': outcome,
    },
  );

  /// Marks the worker as stopped. Any execution it was still running is
  /// recovered by the sweeper via lease expiry.
  _ida.Future<void> deregister(_isc.UuidValue workerId) =>
      caller.callServerEndpoint<void>(
        'computeWorker',
        'deregister',
        {'workerId': workerId},
      );
}

/// Machine login endpoint for compute workers. Unauthenticated by design —
/// this is where workers obtain their session.
///
/// Two flavours:
///  * [login] — the cloud Container App Job pool, gated by the shared
///    `computeWorkerSecret` (Key Vault in production).
///  * [loginRemote] — a creator's self-hosted compute client, gated by a
///    revocable per-machine credential minted at `discoman-compute login`.
///    The client never stores the creator's own session: beta refresh tokens
///    are single-use rotating (fragile to persist) and a creator session
///    would grant far more than claim/report rights.
///
/// Both mint standard Serverpod JWT sessions via the auth-core token manager,
/// so workers reuse the exact same client-side session plumbing as the apps.
/// {@category Endpoint}
class EndpointWorkerAuth extends _isc.EndpointRef {
  EndpointWorkerAuth(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'workerAuth';

  /// Exchanges the shared cloud worker secret for a session carrying
  /// `discoman.computeWorker`.
  _ida.Future<_iacc.AuthSuccess> login(String workerSecret) =>
      caller.callServerEndpoint<_iacc.AuthSuccess>(
        'workerAuth',
        'login',
        {'workerSecret': workerSecret},
      );

  /// Exchanges a per-machine compute-client token for a session carrying
  /// `discoman.remoteWorker`, bound (via the credential row) to the creator.
  _ida.Future<_iacc.AuthSuccess> loginRemote(String clientToken) =>
      caller.callServerEndpoint<_iacc.AuthSuccess>(
        'workerAuth',
        'loginRemote',
        {'clientToken': clientToken},
      );
}

/// What a creator's compute client needs to link a script to a project.
///
/// The client reads the script on the creator's own machine and infers its
/// contract there, so the script itself never reaches us. These two calls carry
/// everything else: which projects they can link, and the contract that came
/// out of the one they chose.
/// {@category Endpoint}
class EndpointCreatorScript extends _isc.EndpointRef {
  EndpointCreatorScript(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'creatorScript';

  /// The creator's projects, newest first, for the client's project chooser.
  _ida.Future<List<_i4qtshzf.CreatorProjectSummary>> listProjects() =>
      caller.callServerEndpoint<List<_i4qtshzf.CreatorProjectSummary>>(
        'creatorScript',
        'listProjects',
        {},
      );

  /// Moves a project's waiting runs into the cloud, after its script has been
  /// uploaded.
  ///
  /// Called once the web app has switched a project off the creator's machine.
  /// Runs already queued were stamped for that machine, and a mode change does
  /// not restamp them — so without this, a creator who moved to the cloud
  /// because their machine was overloaded would watch the backlog keep waiting
  /// for exactly that machine.
  ///
  /// Returns how many runs moved.
  _ida.Future<int> migrateQueuedRunsToCloud(String projectId) =>
      caller.callServerEndpoint<int>(
        'creatorScript',
        'migrateQueuedRunsToCloud',
        {'projectId': projectId},
      );

  /// Records the contract the client read from a script on the creator's
  /// machine, and marks the project as running there from now on.
  ///
  /// [fingerprint] identifies the file the contract came from. It is stored but
  /// not yet enforced at run time — a creator who edits their script keeps the
  /// old contract until they publish again.
  _ida.Future<void> publishContract(
    String projectId,
    _idmvvsng.ContractDraft draft,
    String fingerprint,
  ) => caller.callServerEndpoint<void>(
    'creatorScript',
    'publishContract',
    {
      'projectId': projectId,
      'draft': draft,
      'fingerprint': fingerprint,
    },
  );
}

class Modules {
  Modules(Client client) {
    serverpod_auth_idp = _iaic.Caller(client);
    serverpod_auth_core = _iacc.Caller(client);
  }

  late final _iaic.Caller serverpod_auth_idp;

  late final _iacc.Caller serverpod_auth_core;
}

class Client extends _isc.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _isc.MethodCallContext,
      Object,
      StackTrace,
    )?
    onFailedCall,
    Function(_isc.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
    _i85jenna.Client? httpClientOverride,
  }) : super(
         host,
         _il2as5qe.Protocol(),
         securityContext: securityContext,
         streamingConnectionTimeout: streamingConnectionTimeout,
         connectionTimeout: connectionTimeout,
         onFailedCall: onFailedCall,
         onSucceededCall: onSucceededCall,
         disconnectStreamsOnLostInternetConnection:
             disconnectStreamsOnLostInternetConnection,
         httpClientOverride: httpClientOverride,
       ) {
    firebaseIdp = EndpointFirebaseIdp(this);
    jwtRefresh = EndpointJwtRefresh(this);
    computeSettings = EndpointComputeSettings(this);
    computeWorker = EndpointComputeWorker(this);
    workerAuth = EndpointWorkerAuth(this);
    creatorScript = EndpointCreatorScript(this);
    modules = Modules(this);
  }

  late final EndpointFirebaseIdp firebaseIdp;

  late final EndpointJwtRefresh jwtRefresh;

  late final EndpointComputeSettings computeSettings;

  late final EndpointComputeWorker computeWorker;

  late final EndpointWorkerAuth workerAuth;

  late final EndpointCreatorScript creatorScript;

  late final Modules modules;

  @override
  Map<String, _isc.EndpointRef> get endpointRefLookup => {
    'firebaseIdp': firebaseIdp,
    'jwtRefresh': jwtRefresh,
    'computeSettings': computeSettings,
    'computeWorker': computeWorker,
    'workerAuth': workerAuth,
    'creatorScript': creatorScript,
  };

  @override
  Map<String, _isc.ModuleEndpointCaller> get moduleLookup => {
    'serverpod_auth_idp': modules.serverpod_auth_idp,
    'serverpod_auth_core': modules.serverpod_auth_core,
  };
}
